# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0b94d878867011a5a4aa9525a7828736b8b7c8818f199762a7ade56fc4eabc430139859d8b5f971bc01ccc32a513515864649915173739ebdcbbd13dbe98d64

test:
  secret_key_base: d1504148f4bb86d2b80889a35bec89423193e6dcfda431b3045da1405670a31781ba0eb144bb4f66793331bffcf5730386dfcf5606f780227321f600cd99055a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
