# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2525aa019e03e95e69cd8bdb57e4fa7528ea09fae5c8c36c8246593eecfa36fb45e1f084555bc15cbdbb673411621c1304aaa2eab011765baab77c0c21698661

test:
  secret_key_base: 42e5277a579bb5907f1270892b9e7cc9f7b3b497326848a711d465a790e7eae849987ad336b90b22c8a694c2d1f54c5fb3bc8b9b087057d70750f2f8fdf85c8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
